# Generated by Django 4.0.6 on 2022-08-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_employees_hiredate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='hireDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
